<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Initial migration for domain models "User" and "Invoice"
 */
class Version20130924175826 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE typo3_viewhelpertest_domain_model_invoice (persistence_object_identifier VARCHAR(40) NOT NULL, customer VARCHAR(40) DEFAULT NULL, subject VARCHAR(255) NOT NULL, date DATETIME NOT NULL, INDEX IDX_54DE691E81398E09 (customer), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE typo3_viewhelpertest_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, id INT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, newsletter TINYINT(1) NOT NULL, interests LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE typo3_viewhelpertest_domain_model_invoice ADD CONSTRAINT FK_54DE691E81398E09 FOREIGN KEY (customer) REFERENCES typo3_viewhelpertest_domain_model_user (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE typo3_viewhelpertest_domain_model_invoice DROP FOREIGN KEY FK_54DE691E81398E09");
		$this->addSql("DROP TABLE typo3_viewhelpertest_domain_model_invoice");
		$this->addSql("DROP TABLE typo3_viewhelpertest_domain_model_user");
	}
}

?>