TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        providers:
          TestProvider:
            provider: 'PersistedUsernamePasswordProvider'
  Viewhelpertest:
    includeViewHelpers: [alias, base, comment, count, cycle, debug, flashMessages, for, form, form.checkbox, form.hidden, form.select, form.submit, form.textarea, form.textfield, form.upload, format.crop, format.currency, format.date, format.htmlentities, format.htmlentitiesDecode, format.htmlspecialchars, format.json, format.nl2br, format.number, format.padding, format.printf, format.raw, format.stripTags, format.urlencode, groupedFor, if, link.action, link.email, link.external, render, section, security.ifAccess, security.ifAuthenticated, security.ifHasRole, uri.action, uri.email, uri.external, uri.resource]
    someSettingForTestingSettingsInPartials: someSettingValue

    xhprof:
      rootDirectory: '' # path to the XHProf library
      outputDirectory: %FLOW_PATH_DATA%Temporary/Viewhelpertest/XHProf/ # output directory

    profilingTemplatesDirectory: %FLOW_PATH_DATA%Temporary/Viewhelpertest/Fluidtemplates/