
TYPO3:
  Viewhelpertest:
    includeViewHelpers: [alias, base, count, cycle, debug, escape, flashMessages, for, form, form.checkbox, form.hidden, form.select, form.submit, form.textarea, form.textfield, form.upload, format.crop, format.currency, format.date, format.nl2br, format.number, format.padding, format.printf, format.raw, groupedFor, if, link.action, link.email, link.external, render, section, security.ifAccess, security.ifAuthenticated, security.ifHasRole, uri.action, uri.email, uri.external, uri.resource]
    someSettingForTestingSettingsInPartials: someSettingValue

    xhprof:
      rootDirectory: '' # path to the XHProf library
      outputDirectory: %FLOW3_PATH_DATA%Temporary/Viewhelpertest/XHProf/ # output directory

    profilingTemplatesDirectory: %FLOW3_PATH_DATA%Temporary/Viewhelpertest/Fluidtemplates/